name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Postavi Git korisničke podatke
        run: |
          git config --global user.name "Karlo123-byte"
          git config --global user.email "karlo.jozic@ekonomska.edu.ba"

      - name: Automatski commit i push
        run: |
          git add .
          git commit -m "Automatski update $(date)"
          git push origin main
